// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serializer.proto

package ru.nsu.leorita.serializer;

public final class SerializerProto {
  private SerializerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020serializer.proto\"~\n\006Packet\022\031\n\004type\030\001 \002" +
      "(\0162\013.PacketType\022\022\n\nnameLength\030\002 \001(\005\022\020\n\010f" +
      "ilename\030\003 \001(\t\022\017\n\007payload\030\004 \001(\014\022\020\n\010checks" +
      "um\030\005 \001(\t\022\020\n\010filesize\030\006 \001(\003*R\n\nPacketType" +
      "\022\010\n\004INIT\020\000\022\007\n\003ACK\020\001\022\010\n\004DATA\020\002\022\007\n\003END\020\003\022\013" +
      "\n\007SUCCESS\020\004\022\010\n\004FAIL\020\005\022\007\n\003BYE\020\006B.\n\031ru.nsu" +
      ".leorita.serializerB\017SerializerProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new java.lang.String[] { "Type", "NameLength", "Filename", "Payload", "Checksum", "Filesize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
